version: '3.8'

services:
  app:
    build: .
    ports:
      - "8002:8000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: crop_advisory
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
